addons:
    apt:
        packages:
            - silversearcher-ag
        update: true
cache:
    ccache: true
    directories:
        - $HOME/perl_modules
dist: xenial
sudo: false
language: perl
perl:
    - 'blead'
    - '5.26'
matrix:
    allow_failures:
        - perl: 'blead'
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
install:
    # See https://github.com/travis-perl/helpers/issues/42
    - unset AUTHOR_TESTING
    # See https://rt.cpan.org/Public/Bug/Display.html?id=124509
    - cpanm --notest Date::Format || (cat ~/.cpanm/work/*/build.log ; false)
    - cpanm --skip-satisfied Number::Format Path::Tiny Perl::Tidy Test::Code::TidyAll Test::Perl::Critic Test::TrailingSpace || (cat ~/.cpanm/work/*/build.log ; false)
script:
    - make test
